spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root1234!!
    driver-class-name: com.mysql.cj.jdbc.Driver
